### ISSUE TITLE
Template provider was deprecated

### ISSUE THREAD

**Issue by goudev** [oracle-quickstart/oci-arch-hub-spoke#13]
On terraform init: 
Provider registry.terraform.io/hashicorp/template v2.2.0 does not have a package available for your current platform, darwin_arm64.

The Template provider was deprecated and archived before the existence of M1 (darwin_arm64) releases.

**Comment by lfeldman** [comment]
I am using darwin_amd64 on my M1 MacBook. Here is the proof:

<img width="965" alt="image" src="https://user-images.githubusercontent.com/19390609/188158160-126a344e-c2e7-4277-a62c-8d9fc1736ba4.png">
