### ISSUE TITLE
ssh public key parameter

### ISSUE THREAD

**Issue by jgnyshptl** [oracle-quickstart/oci-arch-hub-spoke#2]
hub and spoke TF script is very helpful.  Is ssh_public_key parameter in terraform.tfvars required ?   We are defining same variable in env-var files.
# SSH Keys
ssh_public_key  = "<public_ssh_key_path>"

Thanks

**Comment by oegentil** [comment]
the TF scripts create VMs for testing purposes. that's why you need to include the ssh key. if you comment out the instances, it is not needed. I'll add a note in the readme and I'm also working on change things to be more dynamic.
